
# Postgres
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Jwt
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# Finnhub
finnhub.api-key=${FINNHUB_API_KEY}
finnhub.base-url=${FINNHUB_URL}